config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy]

  get "login" => "author_sessions#new"
  get "logout" => "author_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings

    has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    def tag_list 
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name)}
        self.tags = new_or_found_tags
    end

    def increment_view_count
        self.view_count ||= 0 #check if nil and if so set to 0
        self.view_count += 1
    end

    
    def self.by_year_and_month(year, month)
        dt = DateTime.parse("#{month} #{year}",'%Y %m')
        bom = dt.beginning_of_month
        eom = dt.end_of_month
        where("created_at >= ? and created_at <= ?", bom, eom)
    end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_page

    def set_page
        @articles_months = Article.all.map { |d| d.created_at.strftime('%B') }.uniq
        @articles_years = Article.all.map { |d| d.created_at.strftime('%Y') }.uniq
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper

    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

    def index 
        @top_articles = Article.order(view_count: :desc).limit(3).includes(:tags)
        @number_of_articles = Article.count

        if(!params[:month].blank? && !params[:year].blank?)
            @header_title = "Articles for #{params[:month]}, #{params[:year]}"
            @articles = Article.by_year_and_month(params[:year],params[:month]).order(created_at: :desc).includes(:tags)
        else
            @header_title = "All Articles"
            @articles = Article.order(created_at: :desc).includes(:tags)
        end
    end

    def show
        @article = Article.find(params[:id])

        @article.increment_view_count
        @article.save
        
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.save

        flash.notice = "Article '#{@article.title}' Created!"

        redirect_to article_path(@article)
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' Updated!"

        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        flash.notice = "Article '#{@article.title}' Deleted!"

        redirect_to articles_path
    end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
    def new
    end

    def create
        if login(params[:email], params[:password])
            redirect_back_or_to(articles_path, notice: "Logged in successfully.")
        else
            flash.now.alert = "Login failed."
            render action: :new
        end
    end

    def destroy
        logout
        redirect_to(:authors, notice: "Logged out!")
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_login, except: [:create]
    
    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]

        @comment.save

        redirect_to article_path(@comment.article)
    end

    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :require_login, only: [:destroy]

    def show
        @tag = Tag.find(params[:id])
    end

    def index
        @tags = Tag.all
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        flash.notice = "Tag '#{@tag.name}' Deleted!"

        redirect_to tags_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<ul class="articles">
  <% articles.each do |article|%>
    <li class="article-container">
      <%= link_to article.title, article_path(article), class: "article-title"%>
      <div class="article-content">
        <% if article.image.exists?%>
          <%= link_to image_tag(article.image.url,class: "article-img"), article_path(article)%>
        <%end%>
        <p class="tags-text">
          <% article.tags.each do |tag|%>
            <%= link_to tag.name, tag_path(tag)%>
          <%end%>
        </p>
        <p class="created-text" ><%= image_tag("calendar.png", class: "icon-img")%>Created <%= time_ago_in_words(article.created_at)%> ago</p>
        <p class="view-text"><%= image_tag("eye.png", class: "icon-img")%><%= article.view_count%> views</p>
        <% words = article.body.split(/\W+/) %>
        <p><%= words[0..20].join(' ') %>...</p>
      </div>
    </li>
  <%end%>
</ul>

app/views/articles/_comment.html.erb
<div class="comment-container">
  <h4 class="comment-author"> <%= comment.author_name%></h4>
  <p class="created-text"><%= image_tag("calendar.png", class: "icon-img")%> Posted <%= time_ago_in_words( comment.created_at) %> ago</p>
  <p class="comment"><%=comment.body%></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f|%>
  <ul>
    <% @article.errors.full_messages.each do |error|%>
      <li><%= error%></li>
    <%end%>
  </ul>
  <div class="new-article-container">
    <p>
      <%= f.label :title, class: "textarea-label"%><br/>
      <%= f.text_field :title, class: "author-body",placeholder: "My First Blog!"  %>
    </p>
    <p>
      <%= f.label :body, class: "textarea-label" %><br/>
      <%= f.text_area :body, class: "comment-body",placeholder: "What are your thoughts?" %>
    </p>
    <p>
      <%= f.label :tag_list, class: "textarea-label"%><br/>
      <%= f.text_field :tag_list, class: "tag-body",placeholder: "Ex. Ruby, Programming, Learning..."%>
    </p>
    <% if @article.image.exists?%>
      <%= image_tag @article.image.url, class: "textarea-label"%><br/>
    <%end%>
    <%= f.label :image, "Attach a New Image", class: "textarea-label"%><br/>
    <div class="file-input-wrapper">
      <button class="file-input-button"><%= image_tag("add-image.png", class: "add-image-icon")%> Upload Image</button>
      <%= f.file_field :image%>
    </div>
    <p>
      <%= f.submit "Create Article", class: "submit-button" %>
    </p>
  </div>
<%end%>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: "form"%>

app/views/articles/index.html.erb
<%if  @number_of_articles > 3%>
<h1>Popular Articles</h1>
<%= render partial: "article", locals: {articles: @top_articles}%>
<br>
<br>
<br>
<%end%>
<h1><%= @header_title%></h1>
<% if logged_in?%>
  <%= link_to "Create a New Article", new_article_path, class: "new-article"%>
<%end%>
<%= render partial: "article", locals: {articles: @articles}%>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: "form"%>

app/views/articles/show.html.erb
<%= link_to articles_path, class: "back-button" do%>
    <%=image_tag("arrow.png", class: "icon-img")%> Back to Articles List
<%end%>
<div class="article-container">
  <h1 class="article-title"><%= @article.title%></h1>
  <div class="article-content">
    <p class="tags-text">
      <% @article.tags.each do |tag|%>
        <%= link_to tag.name, tag_path(tag)%>
      <%end%>
    </p>
    <p class="created-text" ><%= image_tag("calendar.png", class: "icon-img")%>Created <%= time_ago_in_words(@article.created_at)%> ago</p>
    <p class="view-text"><%= image_tag("eye.png", class: "icon-img")%><%= @article.view_count%> views</p>
    <% if @article.image.exists?%>
      <%= image_tag @article.image.url,class: "article-img"%>
    <%end%>
    <p><%= @article.body%></p>
  </div>
  <div id="article-button-container">
    <% if logged_in?%>
      <%= link_to edit_article_path(@article), class: "edit-button" do%>
        <%=image_tag("pencil.png", class: "icon-img")%> Edit
      <%end%>
      <%= link_to  article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}, class: "delete-button" do%>
        <%= image_tag("delete.png", class: "icon-img")%> Delete
      <%end%>
    <%end%>
  </div>
</div>
<hr></hr>
<div class="comments-container">
  <h3 class="comments-title">Comments (<%= @article.comments.size%>)</h3>
  <%= render partial: "comments/form"%>
  <%= render partial: "articles/comment", collection: @article.comments%>
</div>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do%>
<div class="author-container">
    <div class="author-info-label">
        <%= label_tag :email, "Email:"%>
        <%= text_field_tag :email, "", class: "author-body"%>
    </div>
    <div class="author-info-label">
        <%= label_tag :password, "Password:"%>
        <%= password_field_tag :password, "", class: "author-body"%>
    </div>

        <%= submit_tag "Login", class: "submit-button"%>
</div>
<%end%>
<br></br>
<%= link_to  articles_path, class: "back-button" do%>
    <%=image_tag("arrow.png", class: "icon-img")%> Back
<%end%>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="author-container">
    <div class="author-info-label">
      <%= form.label :username, class:"comment-author" %>
      <%= form.text_field :username, class: "tag-body" %>
    </div>
    <div class="author-info-label">
      <%= form.label :email, class:"comment-author" %>
      <%= form.text_field :email, class: "tag-body" %>
    </div>
    <div class="author-info-label">
      <%= form.label :password, class:"comment-author" %>
      <%= form.password_field  :password, class: "tag-body" %>
    </div>
    <div class="author-info-label">
      <%= form.label :password_confirmation, class:"comment-author" %>
      <%= form.password_field :password_confirmation, class: "tag-body" %>
    </div>
    <div class="author-info-label">
      <%= form.submit "Update Author", class: "edit-button" %>
    </div>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>
<br></br>
<%= link_to @author, class: "back-button" do%>
    <%=image_tag("arrow.png", class: "icon-img")%> All Authors
<%end%>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Authors</h1>
<table class="author-container" >
  <thead class="author-info-header">
    <tr>
      <th id="username-title">Username</th>
      <th>Email</th>
      <th colspan="3"></th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr class="author-row">
        <td class="comment"><%= author.username %></td>
        <td class="comment"><%= author.email %></td>
        <td> <%= link_to  "More Info", author, class: "submit-button"%></td>
        <td> <%= link_to edit_author_path(author), class: "submit-button"  do%>
            <%=image_tag("pencil.png", class: "icon-img")%> Edit
          <%end%>
        </td>
        <td>
          <%= link_to author, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" do%>
            <%= image_tag("delete.png", class: "icon-img")%> Delete
          <%end%>
        </td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Author', new_author_path, class: "new-article" %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form', author: @author %>
<br></br>
<%= link_to authors_path, class: "back-button" do%>
    <%=image_tag("arrow.png", class: "icon-img")%> Back
<%end%>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="author-container">
  <p class="author-info-label">
    <strong class="comment-author">Username:</strong>
    <%= @author.username %>
  </p>
  <p class="author-info-label">
    <strong class="comment-author">Email:</strong>
    <%= @author.email %>
  </p>
  <br>
</br>
<%= link_to edit_author_path(@author), class: "edit-button"  do%>
  <%=image_tag("pencil.png", class: "icon-img")%> Edit
<%end%>
<br>
</br>
</div>
<br>
</br>
<%= link_to authors_path, class: "back-button" do%>
    <%=image_tag("arrow.png", class: "icon-img")%> Back to Authors List
<%end%>

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment] do |f|%>
<div class="comment-container">
    <p class="comment-author">
        <%= f.label :author_name, "Comment as" %><br/>
        <%= f.text_field :author_name, class: "author-body",placeholder: "Who are you?"%>
    </p>
    <p class="textarea-label">
        <%= f.label :body, "Comment:" %><br/>
    </p>
        <%= f.text_area :body, class: "comment-body",placeholder: "What are your thoughts?"%>
        <%= f.submit "Post", class: "submit-button"%>
        </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= auto_discovery_link_tag :rss, articles_path(:format => :rss) %>
  </head>
  <body>
    <p class="flash"><%= flash.notice %></p>
    <div class="sidenav">
      <div id="navbar-header">
        <div id="ruby-icon" class="article-img"></div>
        <div id="navbar-header-text">Blog with Rails</div>
      </div>
      <% if logged_in?%>
        <%= link_to "#{current_user.username}", authors_path, :id => "username"%>
      <%else%>
              <br>
      <%end%>
      <%= link_to "Articles", articles_path%>
      <%= link_to "Tags", tags_path%>
      <% if logged_in?%>
        <%= link_to "New Article", new_article_path%>
        <%= link_to "Logout", logout_path%>
      <%else%>
        <%= link_to "Login", login_path%>
      <%end%>
      <div id=archive>
        <%= form_with url: articles_path, method: :get, authenticity_token: true, local: true do |form|%>
          <p>Archive:</p>
          <div id=archive-select>
            <%= form.select "month", options_for_select(@articles_months), include_blank: "Month" %>
            <%= form.select "year", options_for_select(@articles_years), include_blank: "Year" %>
          </div>
          <%= form.submit 'Search'%>
        <%end%>
      </div>
      <div class="navbar-footer">
        <%= link_to image_tag("feed-icon-24x24.gif", :id => "rss-icon"), articles_path(format: "rss"), :id => "rss-link"%>
        <%= link_to( "https://gitlab.com/asuar/blogger", :id => "gitlab-link") do%>
            <div id="gitlab-icon"></div>
        <%end%>
        <p>© 2019 Alain Suarez</p>
      </div>
    </div>
    <div id="container">
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul id="tags">
  <% @tags.each do |tag|%>
    <li class="tags-container">
      <%= link_to tag.name, tag_path(tag), class: "tags-link"%>
      <% if logged_in?%>
        <%= link_to tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"}, class: "delete-button" do%>
          <%= image_tag("delete.png", class: "icon-img")%> Delete
        <%end%>
      <%end%>
    </li>
  <%end%>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name%></h1>

<ul>
    <% @tag.articles.each do |article|%>
        <li class="tags-container"><%= link_to article.title, article_path(article), class: "tags-link"%></li>
    <%end%>
</ul>